// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: list_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId    string  `protobuf:"bytes,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceGte  float64 `protobuf:"fixed64,4,opt,name=price_gte,json=priceGte,proto3" json:"price_gte,omitempty"`
	PriceLte  float64 `protobuf:"fixed64,5,opt,name=price_lte,json=priceLte,proto3" json:"price_lte,omitempty"`
	WeightGte float64 `protobuf:"fixed64,6,opt,name=weight_gte,json=weightGte,proto3" json:"weight_gte,omitempty"`
	WeightLte float64 `protobuf:"fixed64,7,opt,name=weight_lte,json=weightLte,proto3" json:"weight_lte,omitempty"`
}

func (x *ListProductReq) Reset() {
	*x = ListProductReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReq) ProtoMessage() {}

func (x *ListProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_list_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReq.ProtoReflect.Descriptor instead.
func (*ListProductReq) Descriptor() ([]byte, []int) {
	return file_list_product_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductReq) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ListProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProductReq) GetPriceGte() float64 {
	if x != nil {
		return x.PriceGte
	}
	return 0
}

func (x *ListProductReq) GetPriceLte() float64 {
	if x != nil {
		return x.PriceLte
	}
	return 0
}

func (x *ListProductReq) GetWeightGte() float64 {
	if x != nil {
		return x.WeightGte
	}
	return 0
}

func (x *ListProductReq) GetWeightLte() float64 {
	if x != nil {
		return x.WeightLte
	}
	return 0
}

type ListProductRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *ListProductRes) Reset() {
	*x = ListProductRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRes) ProtoMessage() {}

func (x *ListProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_list_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRes.ProtoReflect.Descriptor instead.
func (*ListProductRes) Descriptor() ([]byte, []int) {
	return file_list_product_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductRes) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_list_product_proto protoreflect.FileDescriptor

var file_list_product_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x67,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x69, 0x63, 0x65, 0x47,
	0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x74, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x67, 0x74, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x47, 0x74, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6c, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x4c, 0x74, 0x65, 0x22, 0x37, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x32, 0x4d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68, 0x69, 0x73, 0x2d, 0x49, 0x73, 0x2d, 0x50, 0x72, 0x69, 0x6e,
	0x63, 0x65, 0x2f, 0x61, 0x67, 0x72, 0x69, 0x2d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_list_product_proto_rawDescOnce sync.Once
	file_list_product_proto_rawDescData = file_list_product_proto_rawDesc
)

func file_list_product_proto_rawDescGZIP() []byte {
	file_list_product_proto_rawDescOnce.Do(func() {
		file_list_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_list_product_proto_rawDescData)
	})
	return file_list_product_proto_rawDescData
}

var file_list_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_list_product_proto_goTypes = []interface{}{
	(*ListProductReq)(nil), // 0: pb.ListProductReq
	(*ListProductRes)(nil), // 1: pb.ListProductRes
	(*Product)(nil),        // 2: pb.Product
}
var file_list_product_proto_depIdxs = []int32{
	2, // 0: pb.ListProductRes.product:type_name -> pb.Product
	0, // 1: pb.ListProductService.ListProduct:input_type -> pb.ListProductReq
	1, // 2: pb.ListProductService.ListProduct:output_type -> pb.ListProductRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_list_product_proto_init() }
func file_list_product_proto_init() {
	if File_list_product_proto != nil {
		return
	}
	file_search_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_list_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProductReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_list_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProductRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_list_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_list_product_proto_goTypes,
		DependencyIndexes: file_list_product_proto_depIdxs,
		MessageInfos:      file_list_product_proto_msgTypes,
	}.Build()
	File_list_product_proto = out.File
	file_list_product_proto_rawDesc = nil
	file_list_product_proto_goTypes = nil
	file_list_product_proto_depIdxs = nil
}
