// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchNearbyShop(ctx context.Context, in *SearchNearbyShopReq, opts ...grpc.CallOption) (*SearchNearbyShopRes, error)
	SearchByProduct(ctx context.Context, in *SearchByProductReq, opts ...grpc.CallOption) (*SearchByProductRes, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchNearbyShop(ctx context.Context, in *SearchNearbyShopReq, opts ...grpc.CallOption) (*SearchNearbyShopRes, error) {
	out := new(SearchNearbyShopRes)
	err := c.cc.Invoke(ctx, "/pb.SearchService/SearchNearbyShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchByProduct(ctx context.Context, in *SearchByProductReq, opts ...grpc.CallOption) (*SearchByProductRes, error) {
	out := new(SearchByProductRes)
	err := c.cc.Invoke(ctx, "/pb.SearchService/SearchByProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	SearchNearbyShop(context.Context, *SearchNearbyShopReq) (*SearchNearbyShopRes, error)
	SearchByProduct(context.Context, *SearchByProductReq) (*SearchByProductRes, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchNearbyShop(context.Context, *SearchNearbyShopReq) (*SearchNearbyShopRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchNearbyShop not implemented")
}
func (UnimplementedSearchServiceServer) SearchByProduct(context.Context, *SearchByProductReq) (*SearchByProductRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByProduct not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchNearbyShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNearbyShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchNearbyShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SearchService/SearchNearbyShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchNearbyShop(ctx, req.(*SearchNearbyShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SearchService/SearchByProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchByProduct(ctx, req.(*SearchByProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchNearbyShop",
			Handler:    _SearchService_SearchNearbyShop_Handler,
		},
		{
			MethodName: "SearchByProduct",
			Handler:    _SearchService_SearchByProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
